apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim3
  namespace: egs8sneakerstore
  labels:
    app: mariadb-product
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200M
---
apiVersion: apps/v1
kind: Deployment # what to create?
metadata:
  name: mariadb-product
  namespace: egs8sneakerstore
spec: # specification for deployment resource
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: mariadb-product
  template: # blueprint for pods
    metadata:
      labels:
        app: mariadb-product # service will look for this label
    spec: # specification for pods
      containers: # we can have one or more containers
      - name: mariadb
        image: elmacias66/mariadb:latest
        ports:
        - containerPort: 3306 
        env:
        #- name: MARIADB_RANDOM_ROOT_PASSWORD
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          value: "0" # if it is 1 and root_password is set, root_password takes precedance
        - name: MARIADB_ROOT_PASSWORD
          value: secret
        volumeMounts:
        - name: mariadb-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-pv
        persistentVolumeClaim:
          claimName: mariadb-pv-claim3
---
apiVersion: v1
kind: Service
metadata:
  name: productmariadb 
  namespace: egs8sneakerstore
spec:
  selector:
    app: mariadb-product
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
